// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI5CXdtzATyXHw-FuHIeS-08Os3mksu4E',
    appId: '1:675898476082:web:ba0ef67ce76df9fc7d5e2b',
    messagingSenderId: '675898476082',
    projectId: 'competition-flutter',
    authDomain: 'competition-flutter.firebaseapp.com',
    storageBucket: 'competition-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMClulnBAImIb_Gp9w67LGvfBZbFZr1Zo',
    appId: '1:675898476082:android:82cee6fb942e434b7d5e2b',
    messagingSenderId: '675898476082',
    projectId: 'competition-flutter',
    storageBucket: 'competition-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoy5f8SqwOY5OqyBhXOnCMKxQ8LOyzA94',
    appId: '1:675898476082:ios:47b9c85e49f5eb947d5e2b',
    messagingSenderId: '675898476082',
    projectId: 'competition-flutter',
    storageBucket: 'competition-flutter.appspot.com',
    iosBundleId: 'com.example.createProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoy5f8SqwOY5OqyBhXOnCMKxQ8LOyzA94',
    appId: '1:675898476082:ios:47b9c85e49f5eb947d5e2b',
    messagingSenderId: '675898476082',
    projectId: 'competition-flutter',
    storageBucket: 'competition-flutter.appspot.com',
    iosBundleId: 'com.example.createProject',
  );
}
